(function(root){'use strict';
const types=['Downlight','Wall light','Spotlight','Pendant','Linear','Track spotlight','Track wallwasher','LED strip','Bollard','In-ground uplight','Surface uplight','Spike spotlight','Floodlight','Wallwasher','Wall grazer','Step light','Pole light','Other'];
const components=['Track length','Power feed','Straight connector','L connector','T connector','X connector','Flexible connector','End cap','Suspension kit','Mounting kit','Profile','Diffuser','Driver','Controller','Cable','Other'];
const supply=['Included','Separate supply','By others','Not required'];
const fields=[
['tag','Tag','text',11],['image','Product image','image',20],['scope','Environment','text',14],['floor','Floor / level','text',16],['area','Area / location','text',20],['type','Luminaire type','text',20],['systemId','System ID','text',13],['description','Description','text',34],['manufacturer','Manufacturer','text',20],['model','Family / model','text',20],['orderCode','Ordering code','text',24],['power','Power per unit (W)','number',13],['powerBasis','Power basis','text',16],['lumens','Lumens per unit','number',13],['cct','CCT (K)','number',11],['cri','CRI','number',9],['beam','Beam / distribution','text',18],['ip','IP rating','text',10],['ik','IK rating','text',10],['mounting','Mounting','text',16],['dimensions','Dimensions (mm)','text',20],['cutout','Cut-out (mm)','text',17],['finish','Finish','text',16],['material','Material','text',16],['driver','Driver arrangement','text',18],['control','Control','text',15],['driverSupply','Driver supply','text',16],['unit','Unit','text',9],['quantity','Quantity','number',11],['load','Scheduled power (W)','number',16],['datasheet','Datasheet reference','text',24],['notes','Notes','text',30],['rate','Unit rate','number',12],['amount','Amount','number',14]
].map(([key,label,type,width])=>({key,label,type,width}));
const accessoryFields=[['ref','Component ref.','text',14],['image','Product image','image',20],['systemId','System ID','text',14],['scope','Environment','text',14],['floor','Floor / level','text',16],['area','Area / location','text',20],['component','Component type','text',20],['description','Description','text',32],['manufacturer','Manufacturer','text',20],['orderCode','Ordering code','text',22],['pieceLength','Piece length (m)','number',15],['size','Dimensions / size','text',20],['unit','Unit','text',9],['quantity','Quantity','number',12],['totalLength','Scheduled length (m)','number',18],['supply','Supply scope','text',18],['driverCapacity','Driver rating (W)','number',16],['finish','Finish / IP','text',18],['systemFamily','System family','text',20],['voltage','System voltage / type','text',20],['datasheet','Datasheet reference','text',24],['notes','Notes','text',30],['rate','Unit rate','number',12],['amount','Amount','number',14]].map(([key,label,type,width])=>({key,label,type,width}));
const uid=()=>globalThis.crypto?.randomUUID?.()||'id-'+Date.now()+'-'+Math.random().toString(16).slice(2);
const clone=x=>JSON.parse(JSON.stringify(x));
function unitFor(r,key){return ({power:r.unit==='m'?'W/m':'W',lumens:r.unit==='m'?'lm/m':'lm',cct:'K',beam:/^\s*\d+(\.\d+)?\s*$/.test(String(r.beam??''))?'°':'',quantity:r.unit||'pcs',load:'W',pieceLength:'m',totalLength:'m',driverCapacity:'W',dimensions:'mm',size:'mm',cutout:'mm'})[key]||'';}
function formatValue(r,key,v){if(v==null||v==='')return '';let unit=unitFor(r,key),text=typeof v==='number'?v.toLocaleString('en-GB',{maximumFractionDigits:3,useGrouping:!['cct','cri','beam'].includes(key)}):String(v);if(key==='ip'&&/^\d+$/.test(text))return 'IP'+text;if(key==='ik'&&/^\d+$/.test(text))return 'IK'+text.padStart(2,'0');if(!unit)return text;if(unit==='°')return text+'°';if(new RegExp('(?:^|\\s)'+unit.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$','i').test(text))return text;return text+' '+unit;}
function columns(fs,keys){return fs.map(f=>({...f,visible:keys.includes(f.key)})).sort((a,b)=>{let ai=keys.indexOf(a.key),bi=keys.indexOf(b.key);return(ai<0?999:ai)-(bi<0?999:bi);});}
function newProject(){return{schemaVersion:1,id:uid(),meta:{name:'Untitled project',client:'',company:'',consultant:'',number:'',document:'',revision:'P01',date:new Date().toISOString().slice(0,10),purpose:'For Review',prepared:'',checked:'',approved:'',currency:'AED',notes:'',logo:''},luminaires:[],systems:[],accessories:[],customFields:[],output:{autoFill:true,stretchRows:true,rowHeight:12,cellBorders:'rows',pageBorder:false,borderColor:'#B8C0C4',borderWidth:0.2,aggregateBOQ:false,pageBreakScope:false,pageBreakFloor:false,autoFit:true,fontFamily:'Roboto',kind:'schedule',scope:'All',floor:'All',area:'All',grouping:['scope','floor','type'],pageSize:'A3',orientation:'landscape',fontSize:10,rowsPerPage:6,showEmpty:true,includeAccessories:true,columns:columns(fields,['tag','image','description','manufacturer','orderCode','power','lumens','cct','cri','beam','ip','control','unit','quantity']),boqColumns:columns(fields,['tag','description','manufacturer','orderCode','unit','quantity']),accessoryColumns:columns(accessoryFields,['ref','systemId','component','description','manufacturer','orderCode','pieceLength','unit','quantity','supply'])}};}
const number=x=>x===''||x==null?null:(Number.isFinite(Number(x))?Number(x):null);
function rowValue(r,k){if(k==='load'){const p=number(r.power),q=number(r.quantity);return p===null||q===null?null:p*q;}if(k==='amount'){const p=number(r.rate),q=number(r.quantity);return p===null||q===null?null:p*q;}if(k==='totalLength'){let q=number(r.quantity);if(q===null)return null;if(r.unit==='m')return q;let len=number(r.pieceLength);return r.unit==='pcs'&&len!==null?q*len:null;}return r[k]??'';}
function enrich(project,records){return records.map(r=>{let s=project.systems.find(s=>s.id===r.systemId||s.code===r.systemId);return{...r,systemId:s?.code||r.systemId||'',scope:r.scope||s?.scope||'',floor:r.floor||s?.floor||'',area:r.area||s?.area||'',systemFamily:s?.family||'',voltage:r.voltage||s?.voltage||''};});}
function selected(project,kind){const o=project.output;return enrich(project,kind==='accessories'?project.accessories:project.luminaires).filter(r=>['scope','floor','area'].every(k=>o[k]==='All'||!o[k]||r[k]===o[k]));}

// Only exact technical matches with a known manufacturer and ordering code can merge.
function aggregate(rows){const ignored=new Set(['id','quantity','tag','ref','scope','floor','area','systemId','image','attachment','datasheet','specSheet']);const groups=new Map();for(const r of rows){const keys=Object.keys(r).filter(k=>!ignored.has(k)&&r[k]!==''&&r[k]!=null).sort();const eligible=String(r.orderCode||'').trim()&&String(r.manufacturer||'').trim()&&number(r.quantity)!==null;const sig=eligible?JSON.stringify(keys.map(k=>[k,r[k]])):uid();if(!groups.has(sig))groups.set(sig,[]);groups.get(sig).push(r);}return [...groups.values()].map(rs=>{const out={...rs[0]};if(rs.length===1)return out;out.quantity=rs.reduce((n,r)=>n+number(r.quantity),0);for(const k of ['tag','ref','scope','floor','area','systemId','datasheet'])out[k]=[...new Set(rs.map(r=>r[k]).filter(Boolean))].join(', ');out.sourceIds=rs.map(r=>r.id);return out;});}
function makeTemplate(p,name){const output=clone(p.output);for(const k of ['scope','floor','area'])delete output[k];return {templateVersion:1,id:uid(),name:String(name).trim(),output,customFields:clone(p.customFields)};}
function applyTemplate(p,t){if(!t||t.templateVersion!==1||!t.name||!t.output||!Array.isArray(t.customFields))throw Error('Invalid output template.');const draft=clone(p),filters={scope:p.output.scope,floor:p.output.floor,area:p.output.area};draft.output={...newProject().output,...clone(t.output),...filters};for(const k of ['columns','boqColumns','accessoryColumns']){if(!Array.isArray(draft.output[k]))throw Error('Invalid template columns.');const keys=new Set(draft.output[k].map(c=>c.key));draft.output[k].push(...p.output[k].filter(c=>!keys.has(c.key)).map(c=>({...c,visible:false})));}for(const f of t.customFields){if(!f||typeof f.key!=='string'||!f.key.startsWith('custom_'))throw Error('Invalid custom field.');const old=draft.customFields.find(x=>x.key===f.key);if(old&&(old.type!==f.type||old.unit!==f.unit))throw Error('Custom field conflict: '+f.label);if(!old)draft.customFields.push(clone(f));}return validateImport(draft);}
function labelFor(k){return ({scope:'Environment',floor:'Floor / level',area:'Area / location',type:'Luminaire type',systemId:'System',component:'Component type'})[k]||k;}
function groupRows(rows,keys,depth=0){if(depth===keys.length)return rows.map(r=>({kind:'item',record:r}));const key=keys[depth],map=new Map();for(const r of rows){const v=String(r[key]??'').trim();if(!map.has(v))map.set(v,[]);map.get(v).push(r);}return [...map].sort((a,b)=>key==='scope'?({Indoor:0,Outdoor:1}[a[0]]??2)-({Indoor:0,Outdoor:1}[b[0]]??2):0).flatMap(([value,rs])=>[...(value?[{kind:'group',level:depth,key,label:value,count:rs.length}]:[]),...groupRows(rs,keys,depth+1)]);}
function alignment(c){return ['left','center','right'].includes(c.align)?c.align:(c.type==='number'?'right':'left');}
function fitWidth(c,rows){if(c.type==='image')return 14;const values=[c.label,...rows.map(r=>{const v=rowValue(r,c.key);return c.unit&&v!==''&&v!=null?String(v)+' '+c.unit:formatValue(r,c.key,v);})];const lengths=values.flatMap(v=>String(v||'').split('\n').map(x=>Array.from(x).reduce((n,ch)=>n+(/[MW@]/.test(ch)?1.4:/[il.,: ]/.test(ch)?.5:1),0)));return Math.min(c.type==='number'?24:38,Math.max(7,Math.ceil(Math.max(...lengths,0)+2)));}
function outputColumns(project,kind){const o=project.output,rows=o.autoFit?selected(project,kind):[];return (kind==='accessories'?o.accessoryColumns:o.kind==='boq'?o.boqColumns:o.columns).filter(c=>c.visible).map(c=>({...c,align:alignment(c),width:o.autoFit?fitWidth(c,rows):c.width}));}
function totals(rows){const x={pcs:0,m:0,set:0,load:0,loadIncomplete:false,hasLED:false,amount:0,amountIncomplete:false};for(const r of rows){let q=number(r.quantity);if(q!==null&&Object.hasOwn(x,r.unit))x[r.unit]+=q;let power=rowValue(r,'load');if(power===null)x.loadIncomplete=true;else x.load+=power;if(r.powerBasis==='LED load')x.hasLED=true;let am=rowValue(r,'amount');if(am===null)x.amountIncomplete=true;else x.amount+=am;}return x;}
function checks(p){const list=[];function add(kind,r,message){list.push({kind,id:r.id,tag:r.tag||r.ref||r.code||'Untitled',message});}const codes=new Set();for(const s of p.systems){if(!s.code)add('system',s,'System code is missing');if(codes.has(s.code))add('system',s,'Duplicate system code');codes.add(s.code);}
 const tags=new Set();for(const r of p.luminaires){if(!r.tag)add('luminaire',r,'Tag is missing');if(tags.has(r.tag))add('luminaire',r,'Duplicate tag; combine quantities or use a distinct tag');tags.add(r.tag);for(const [k,l] of [['description','Description'],['manufacturer','Manufacturer'],['orderCode','Ordering code'],['scope','Environment'],['floor','Floor / level'],['type','Luminaire type'],['unit','Unit'],['powerBasis','Power basis']])if(!r[k])add('luminaire',r,l+' is missing');for(const k of ['quantity','power','lumens','cct','cri'])if(number(r[k])===null)add('luminaire',r,labelFor(k)+' is missing');if(r.systemId&&!p.systems.some(s=>s.id===r.systemId||s.code===r.systemId))add('luminaire',r,'System link is missing');if(['Track spotlight','Track wallwasher','LED strip'].includes(r.type)&&!r.systemId)add('luminaire',r,'Assign a system');if(r.mounting==='Recessed'&&!r.cutout)add('luminaire',r,'Cut-out is missing');if(r.powerBasis==='LED load')add('luminaire',r,'LED load excludes upstream driver losses');}
 const refs=new Set();for(const r of p.accessories){if(!r.ref)add('accessory',r,'Component reference is missing');if(refs.has(r.ref))add('accessory',r,'Duplicate component reference');refs.add(r.ref);if(!p.systems.some(s=>s.id===r.systemId||s.code===r.systemId))add('accessory',r,'Assign an existing system');if(number(r.quantity)===null)add('accessory',r,'Quantity is missing');if(!r.supply)add('accessory',r,'Supply scope is missing');if(r.component==='Track length'&&r.unit==='pcs'&&number(r.pieceLength)===null)add('accessory',r,'Enter the piece length for track supplied in pieces');if(r.component==='Driver'&&number(r.driverCapacity)===null)add('accessory',r,'Driver rated capacity is missing');}return list;}
function validateImport(p){if(!p||p.schemaVersion!==1||typeof p.id!=='string'||!p.meta||typeof p.meta.name!=='string')throw Error('This is not a Luminaire Studio v1 project.');for(const k of ['luminaires','systems','accessories','customFields'])if(!Array.isArray(p[k]))throw Error('Project structure is incomplete: '+k);if(p.luminaires.length+p.accessories.length>10000)throw Error('This project exceeds the 10,000-row limit.');const base=newProject();p.output={...base.output,...p.output};for(const k of ['columns','boqColumns','accessoryColumns']){if(!Array.isArray(p.output[k]))p.output[k]=base.output[k];p.output[k]=p.output[k].filter(c=>c&&typeof c.key==='string'&&typeof c.label==='string').map(c=>({...c,align:alignment(c),width:Math.min(60,Math.max(6,Number(c.width)||16))}));}for(const k of ['aggregateBOQ','pageBreakScope','pageBreakFloor'])p.output[k]=p.output[k]===true;p.output.autoFit=Boolean(p.output.autoFit);p.output.fontFamily=String(p.output.fontFamily||'Roboto').replace(/[^a-zA-Z0-9 _-]/g,'').slice(0,80)||'Arial';p.output.grouping=(p.output.grouping||[]).filter(k=>['scope','floor','area','type','systemId'].includes(k));p.output.rowsPerPage=Math.max(1,Math.min(100,Number(p.output.rowsPerPage)||6));p.output.fontSize=Math.max(7,Math.min(16,Number(p.output.fontSize)||10));p.output.pageSize=['A3','A4'].includes(p.output.pageSize)?p.output.pageSize:'A3';p.output.orientation=p.output.orientation==='portrait'?'portrait':'landscape';for(const k of ['luminaires','systems','accessories'])for(const r of p[k]){if(!r||typeof r!=='object'||Array.isArray(r))throw Error('Invalid record');if(!r.id)r.id=uid();for(const c of ['quantity','power','lumens','cct','cri','rate','pieceLength','driverCapacity'])if(r[c]!==''&&r[c]!=null&&(number(r[c])===null||number(r[c])<0))throw Error('Invalid numeric value: '+c);}for(const r of [p.meta,...p.luminaires,...p.accessories])for(const k of ['image','logo'])if(r[k]&&!/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=\s]+$/.test(r[k]))throw Error('Project images must be embedded PNG or JPEG files.');return p;}
function demo(){const p=newProject();p.meta={...p.meta,name:'Sample lighting project',client:'Demonstration only',document:'LS-DEMO-001',notes:'Illustrative data only. Replace with verified manufacturer specifications before client issue.'};const a={id:uid(),code:'TR-01',type:'Track system',scope:'Indoor',floor:'Ground floor',area:'Gallery',family:'Demo track family',manufacturer:'Example brand',voltage:'Mains track',mounting:'Surface'};const b={id:uid(),code:'LS-01',type:'LED strip system',scope:'Outdoor',floor:'Ground level',area:'Facade',family:'Demo linear family',voltage:'24 V DC'};p.systems=[a,b];const base={manufacturer:'Example brand',powerBasis:'System input',cct:3000,cri:90,finish:'White',unit:'pcs',driver:'Integral',control:'On/Off',driverSupply:'Included'};p.luminaires=[{...base,id:uid(),tag:'DL01',scope:'Indoor',floor:'Ground floor',area:'Lobby',type:'Downlight',description:'Recessed fixed downlight',orderCode:'DEMO-DL',power:10,lumens:850,beam:'36°',ip:'IP44',mounting:'Recessed',dimensions:'Ø90 × 100',cutout:'Ø80',quantity:12},{...base,id:uid(),tag:'TL01',scope:'Indoor',floor:'Ground floor',area:'Gallery',type:'Track spotlight',systemId:a.id,description:'Adjustable track spotlight',orderCode:'DEMO-TL',power:18,lumens:1500,beam:'24°',ip:'IP20',quantity:8},{...base,id:uid(),tag:'WL01',scope:'Indoor',floor:'First floor',area:'Corridor',type:'Wall light',description:'Wall-mounted luminaire',orderCode:'DEMO-WL',power:8,lumens:550,beam:'Diffuse',ip:'IP20',quantity:6},{...base,id:uid(),tag:'LS01',scope:'Outdoor',floor:'Ground level',area:'Facade',type:'LED strip',systemId:b.id,description:'Linear LED strip',orderCode:'DEMO-LS',power:12,powerBasis:'LED load',lumens:1000,beam:'Diffuse',ip:'IP67',unit:'m',quantity:15,driver:'Remote',driverSupply:'Separate supply'}];p.accessories=[{id:uid(),ref:'TR-A01',systemId:a.id,component:'Track length',description:'Track section',manufacturer:'Example brand',orderCode:'DEMO-TRACK',pieceLength:2,unit:'pcs',quantity:4,supply:'Separate supply'},{id:uid(),ref:'TR-A02',systemId:a.id,component:'Power feed',description:'End power feed',unit:'pcs',quantity:1,supply:'Separate supply'},{id:uid(),ref:'LS-A01',systemId:b.id,component:'Driver',description:'Remote LED driver',driverCapacity:240,unit:'pcs',quantity:1,supply:'Separate supply'}];return p;}
const api={aggregate,makeTemplate,applyTemplate,types,components,supply,fields,accessoryFields,uid,clone,newProject,number,rowValue,unitFor,formatValue,enrich,selected,groupRows,outputColumns,alignment,fitWidth,totals,checks,validateImport,demo,labelFor};root.LS=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
