(function(g){'use strict';const C=g.LS,E=g.LSExport,h=E.esc,px=96/25.4;
function options(p){const o=p.output;return{auto:o.autoFill!==false,row:Math.max(6,Math.min(50,+o.rowHeight||12)),borders:['none','rows','all'].includes(o.cellBorders)?o.cellBorders:'rows',color:/^#[a-f0-9]{6}$/i.test(o.borderColor)?o.borderColor:'#B8C0C4',line:Math.max(.1,Math.min(1,+o.borderWidth||.2)),frame:!!o.pageBorder,margin:8};}
function dims(p){const a=p.output.pageSize==='A3'?[297,420]:[210,297];return p.output.orientation==='landscape'?{w:a[1],h:a[0]}:{w:a[0],h:a[1]};}
function fitScale(width,height,pageWidth,pageHeight){return Math.max(.001,Math.min(Math.max(1,width-16)/pageWidth,Math.max(1,height-16)/pageHeight));}
function manualRows(p,value){p.output.rowsPerPage=Math.max(1,Math.min(100,Math.round(Number(value)||1)));p.output.autoFill=false;p.output.rowHeight=Math.round(Math.max(6,Math.min(+p.output.rowHeight||12,(capacity(p)/px-24)/p.output.rowsPerPage))*100)/100;}
function expandedHeights(heights,gap){return heights.map(height=>height+Math.max(0,gap)/Math.max(1,heights.length));}
function rowsFor(s,rs){return C.groupRows(rs,s.groups);}
function key(x){return x.kind==='item'?'i:'+x.record.id:'g:'+x.level+':'+x.key+':'+x.label;}
function pack(p,s,measure,capacity){const q=options(p),pages=[];let batch=[];const push=()=>{if(batch.length){pages.push(batch);batch=[];}};for(const r of s.records){const prev=batch.at(-1),boundary=prev&&!(p.output.kind==='boq'&&p.output.aggregateBOQ)&&((p.output.pageBreakScope&&prev.scope!==r.scope)||(p.output.pageBreakFloor&&(prev.floor!==r.floor||prev.scope!==r.scope)));if(boundary)push();const next=[...batch,r],height=rowsFor(s,next).reduce((sum,x)=>sum+measure(x),0),limit=!q.auto&&batch.length>=p.output.rowsPerPage;if(batch.length&&(height>capacity||limit))push();batch.push(r);}push();return pages;}
function estimatedHeight(p,s,x){const q=options(p),o=p.output;if(x.kind==='group')return 8*px;const width=(dims(p).w-2*q.margin-4)*px,sum=s.columns.reduce((n,c)=>n+c.width,0);let row=q.row*px;for(const c of s.columns){if(c.type==='image')continue;const w=Math.max(12,width*c.width/sum-12),text=E.display(x.record,c,o.showEmpty),chars=Math.max(2,Math.floor(w/(o.fontSize*.56))),lines=String(text).split('\n').reduce((n,t)=>n+Math.max(1,Math.ceil(t.length/chars)),0);row=Math.max(row,lines*o.fontSize*1.25+10);}return row;}
function capacity(p){return (dims(p).h-2*options(p).margin-65)*px;}
function estimatedPages(p,s){return pack(p,s,x=>estimatedHeight(p,s,x),capacity(p));}
function table(p,s,rs){return `<table class="schedule-table"><colgroup>${s.columns.map(c=>`<col style="width:${100*c.width/s.columns.reduce((n,c)=>n+c.width,0)}%">`).join('')}</colgroup><thead><tr>${s.columns.map(c=>`<th style="text-align:${C.alignment(c)}">${h(c.label)}</th>`).join('')}</tr></thead><tbody>${rowsFor(s,rs).map(x=>x.kind==='group'?`<tr data-row-key="${h(key(x))}" class="group g${x.level}"><td colspan="${s.columns.length}">${h(x.label)}</td></tr>`:`<tr data-row-key="${h(key(x))}" class="item">${s.columns.map(c=>`<td style="text-align:${C.alignment(c)}">${c.type==='image'?(x.record.image?`<img class="product" src="${h(x.record.image)}">`:''):h(E.display(x.record,c,p.output.showEmpty))}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
function page(p,s,rs,final,index=1,total=1){const m=p.meta;return `<section class="paper" data-section="${h(s.kind)}"><div class="eyebrow">${h(m.company||'LIGHTING DESIGN')} / ${h(m.purpose)}</div><header><div><h1>${h(s.title)}</h1><div class="project">${h(m.name)}</div></div>${m.logo?`<img class="logo" src="${h(m.logo)}">`:''}</header><div class="meta"><span>CLIENT / ${h(m.client||'—')}</span><span>DOCUMENT / ${h(m.document||'—')}</span><span>REV / ${h(m.revision||'—')}</span><span>${h(m.date||'—')}</span></div>${table(p,s,rs)}<div class="closing">${final?`<div class="summary">${h(E.summary(s))}${s.columns.some(c=>c.key==='amount')?' / '+h(m.currency):''}</div>${m.notes?`<div class="note">${h(m.notes)}</div>`:''}`:''}</div><footer><span>PREPARED / ${h(m.prepared||'—')} · CHECKED / ${h(m.checked||'—')}</span><span class="pagecount">${index} / ${total}</span></footer></section>`;}
function css(p){const q=options(p),d=dims(p),border=`${q.line}mm solid ${q.color}`,o=p.output;return `*{box-sizing:border-box;print-color-adjust:exact;-webkit-print-color-adjust:exact}body{margin:0;background:#e2e5e5;color:#292929;font-family:'${String(o.fontFamily||'Roboto').replace(/[^a-zA-Z0-9 _-]/g,'')}',Arial,sans-serif}.paper{width:${d.w}mm;height:${d.h}mm;padding:${q.margin}mm ${q.margin}mm ${q.margin+8}mm;margin:12px auto;display:flex;flex-direction:column;background:white;position:relative;break-after:page}.paper:last-child{break-after:auto}${q.frame?`.paper:after{content:'';position:absolute;inset:${q.margin-2}mm;border:${border};pointer-events:none}`:''}.paper>*{flex-shrink:0}.eyebrow{background:#ededed;padding:1.2mm 2mm;font-size:9px;letter-spacing:.4px}header{display:flex;align-items:center;justify-content:space-between;gap:5mm;padding:3mm 0}h1{font-family:Montserrat,Arial;font-size:23px;margin:0 0 2mm}.project{font-size:12px;overflow-wrap:anywhere}.logo{width:52mm;height:20mm;object-fit:contain;flex-shrink:0}.meta{display:flex;justify-content:space-between;gap:3mm;padding:2mm 0;margin-bottom:3mm;border-top:1px solid #ddd;border-bottom:1px solid #ddd;font-size:10px;overflow-wrap:anywhere}.meta span{max-width:38%}.schedule-table{border-collapse:collapse;table-layout:fixed;width:100%;font-size:${o.fontSize}px;line-height:1.25}.schedule-table th,.schedule-table td{padding:1.2mm 1.5mm;vertical-align:middle;white-space:pre-wrap;overflow-wrap:anywhere;border:${q.borders==='all'?border:'0'}}${q.borders==='rows'?`.schedule-table th,.schedule-table td{border-bottom:${border}}`:''}.schedule-table th{background:#efefef;font-weight:bold}.item td{height:${q.row}mm}.item:nth-child(even){background:#fafafa}.group td{height:7mm;font-weight:bold;padding:1.2mm 2mm}.g0{background:#d9ddde}.g1{background:#e7e9e9}.g2,.g3{background:#f0f1f1}.g1 td{padding-left:4mm}.g2 td{padding-left:6mm}.g3 td{padding-left:8mm}.product{display:block;width:100%;height:${Math.max(3,q.row-2.4)}mm;object-fit:contain}.closing{font-size:10px}.summary{margin-top:2mm;padding:1.5mm 2mm;background:#efefef}.note{margin-top:2mm;white-space:pre-wrap;overflow-wrap:anywhere}footer{position:absolute;left:${q.margin}mm;right:${q.margin}mm;bottom:${q.margin}mm;margin-top:0;padding-top:2mm;border-top:1px solid #bbb;display:flex;justify-content:space-between;gap:3mm;font-size:9px;min-height:6mm}.paper.oversized{height:auto;min-height:${d.h}mm}.oversized tr{break-inside:auto}tr{break-inside:avoid}.oversized footer{position:static;margin-top:3mm}@page{size:${d.w}mm ${d.h}mm;margin:0}@media print{body{background:white}.paper{margin:0}}`;}
function html(p){const pages=[];for(const s of E.sections(p)){const batches=estimatedPages(p,s);batches.forEach((rs,i)=>pages.push({s,rs,final:i===batches.length-1}));}return `<!doctype html><html><head><meta charset="utf-8"><title>${h(p.meta.name)}</title><style>${g.LSFontCSS||''}${css(p)}</style></head><body>${pages.map((x,i)=>page(p,x.s,x.rs,x.final,i+1,pages.length)).join('')||'<p>No records match this selection.</p>'}</body></html>`;}
async function reflow(doc,p){await doc.fonts.ready;await Promise.all([...doc.images].map(im=>im.decode().catch(()=>{})));doc.body.style.zoom='1';const result=[];for(const s of E.sections(p)){const box=doc.createElement('div');box.style.cssText='position:absolute;left:0;top:0;visibility:hidden;pointer-events:none';box.innerHTML=page(p,s,s.records,true);doc.body.append(box);const paper=box.firstElementChild,table=paper.querySelector('table'),heights=new Map([...table.querySelectorAll('tbody tr')].map(tr=>[tr.dataset.rowKey,tr.getBoundingClientRect().height]));table.querySelector('tbody').innerHTML='';const footer=paper.querySelector('footer'),closing=paper.querySelector('.closing');const available=Math.max(20,footer.getBoundingClientRect().top-table.tHead.getBoundingClientRect().bottom-closing.getBoundingClientRect().height-4);const batches=pack(p,s,x=>heights.get(key(x))??estimatedHeight(p,s,x),available);box.remove();batches.forEach((rs,i)=>result.push({s,rs,final:i===batches.length-1}));}doc.body.innerHTML=result.map((x,i)=>page(p,x.s,x.rs,x.final,i+1,result.length)).join('');await Promise.all([...doc.images].map(im=>im.decode().catch(()=>{})));for(const pg of doc.querySelectorAll('.paper')){const footer=pg.querySelector('footer'),closing=pg.querySelector('.closing');let gap=footer.getBoundingClientRect().top-closing.getBoundingClientRect().bottom-4;if(gap<0){pg.classList.add('oversized');continue;}if(p.output.stretchRows!==false){const rows=[...pg.querySelectorAll('tr.item')];if(rows.length&&gap>1){const heights=rows.map(tr=>tr.getBoundingClientRect().height),expanded=expandedHeights(heights,gap),add=gap/rows.length;rows.forEach((tr,i)=>{tr.style.height=expanded[i]+'px';});const overflow=closing.getBoundingClientRect().bottom-footer.getBoundingClientRect().top+4;if(overflow>0)rows.forEach((tr,i)=>tr.style.height=Math.max(heights[i],heights[i]+add-overflow/rows.length-.2)+'px');}}}return result.length;}

E.printHTML=html;E.reflow=reflow;g.LSPage={options,dims,pack,estimatedPages,estimatedHeight,capacity,css,fitScale,manualRows,expandedHeights};
})(typeof window!=='undefined'?window:globalThis);
